# build container for odbeta with JZ4725 (mips32 w/o fpu), using musl:
# rs90 and similar devices

# libs and compiler from	: odbeta 2021 toolchain

FROM --platform=linux/amd64 debian:bookworm

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils file gcc g++ ca-certificates && \
	apt-get -y --no-install-recommends install

# toolchain and libraries
#RUN	wget --no-check-certificate "https://web.archive.org/web/https://od.abstraction.se/opendingux/toolchain/opendingux-rs90-toolchain.2021-10-22.tar.xz" && \
#	tar xaCf /opt opendingux-rs90-toolchain.2021-10-22.tar.xz
RUN	wget --no-check-certificate "https://github.com/OpenDingux/buildroot/releases/download/od-2022.09.22/opendingux-rs90-toolchain.2022-09-21.tar.xz" && \
	tar xaCf /opt opendingux-rs90-toolchain.2022-09-21.tar.xz

# toolchain definitions
ENV PATH=/opt/rs90-toolchain/usr/bin:$PATH
ENV CROSS_COMPILE=mipsel-linux-
