# build container for odbeta with JZ4770 (mips32r2 w/ fpu), using uclibc:
# gcw0 and similar devices

# libs and compiler from	: odbeta 2021 toolchain

FROM --platform=linux/amd64 debian:bookworm

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils file gcc g++ ca-certificates && \
	apt-get -y --no-install-recommends install

# toolchain and libraries
RUN	wget --no-check-certificate "https://od.abstraction.se/opendingux/toolchain/opendingux-gcw0-toolchain.2021-10-22.tar.xz" && \
	tar xaCf /opt opendingux-gcw0-toolchain.2021-10-22.tar.xz

# toolchain definitions
ENV PATH=/opt/gcw0-toolchain/usr/bin:$PATH
ENV CROSS_COMPILE=mipsel-linux-
