# build container for opendingux with JZ4770:
# gcw-0, rg350/280, gkd350h/mini, and similar devices

# libs from	: opendingux 2014 (updated 2021) toolchain, gcc 4.9
# compiler from	: odbeta 2021 toolchain

# the gcw0 toolchain is x86 32 bit. However, since github blessed us with actions exclusively running on x86 64 bit...
#FROM --platform=linux/386 debian:bookworm
FROM --platform=linux/amd64 debian:bookworm

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils file gcc g++ ca-certificates && \
	apt-get -y --no-install-recommends install libc6-i386 libstdc++6-i386-cross

# toolchain and libraries
# 2014 toolchain uses gcc 4.9, but we can use the current 2021 od beta toolchain's gcc to get a better optimisation
RUN	wget --no-check-certificate "https://od.abstraction.se/opendingux/toolchain/opendingux-gcw0-toolchain.2021-10-22.tar.xz" && \
	tar xaCf /opt opendingux-gcw0-toolchain.2021-10-22.tar.xz && \
	mv /opt/gcw0-toolchain /opt/gcw0-toolchain-od
#RUN	wget --no-check-certificate "https://web.archive.org/web/http://www.gcw-zero.com/files/opendingux-gcw0-toolchain.2014-08-20.tar.bz2" && \
#RUN	wget --no-check-certificate "https://git.libretro.com/libretro-infrastructure/libretro-build-dingux/-/raw/master/toolchain/opendingux-gcw0-toolchain.2014-08-20.tar.bz2" && \
RUN	wget --no-check-certificate "https://github.com/Ninoh-FOX/toolchain/releases/download/08-09-2021/opendingux-gcw0-toolchain.2021-09-08.tar.bz2" && \
	tar xjCf /opt opendingux-gcw0-toolchain.2021-09-08.tar.bz2

# toolchain definitions
# NB on newer GKD firmware there's a problem with missing exception handlers in
# libgcc_s.so. Undefining those functions and linking in libgcc_eh solves this.
ENV PATH=/opt/gcw0-toolchain-od/usr/bin:$PATH
ENV TS=/opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot
ENV CFLAGS="--sysroot $TS -I$TS/usr/include/SDL -mabicalls"
ENV LDFLAGS="$CFLAGS -Wl,--dynamic-linker=/lib/ld-uClibc.so.0 -u__register_frame_info -u__deregister_frame_info -L$TS/../lib -lgcc_eh"
ENV CROSS_COMPILE=mipsel-linux-
