# build container for (open)pandora (OMAP with Cortex A8)

# libs and compiler from : notaz pandora toolchains

FROM --platform=linux/amd64 debian:bullseye

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils file gcc g++ ca-certificates

# toolchain and libraries
RUN	wget --no-check-certificate "https://notaz.gp2x.de/misc/pnd/toolchains/arm-gcc-4.9.4_with_libs.tar.xz" && \
	tar xaCf /opt arm-gcc-4.9.4_with_libs.tar.xz

# toolchain definitions
ENV PATH=/opt/arm-gcc-4.9.4/bin:$PATH
ENV CFLAGS="-I /opt/arm-gcc-4.9.4/arm-unknown-linux-gnueabi/sysroot/usr/local/include"
ENV CROSS_COMPILE=arm-unknown-linux-gnueabi-
