# build container for Retrofw with JZ4760:
# retro game (rs97), rg300, ldk, pap k3, and similar devices 

# libs and compiler from : retrofw-2.3 2022 toolchain
FROM --platform=linux/amd64 debian:bullseye

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils file gcc g++ ca-certificates

# toolchain and libraries
RUN	wget --no-check-certificate "https://github.com/retrofw/retrofw.github.io/releases/download/v2.3/mipsel-RetroFW-linux-uclibc_sdk-buildroot.tar.gz" && \
	tar xzCf /opt mipsel-RetroFW-linux-uclibc_sdk-buildroot.tar.gz

# toolchain definitions
ENV PATH=/opt/mipsel-RetroFW-linux-uclibc_sdk-buildroot/bin:$PATH
ENV CROSS_COMPILE=mipsel-RetroFW-linux-uclibc-
