# build container for GP2X

FROM --platform=linux/386 ubuntu:18.04

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip gcc g++

# toolchain and libraries
# NB arm-none-eabi uses crt0.o as start file, while open2x libs offer crt1.o, so provide a link
RUN	wget --no-check-certificate "https://launchpad.net/gcc-arm-embedded/4.7/4.7-2014-q2-update/+download/gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2" && \
	tar xjCf /opt gcc-arm-none-eabi-4_7-2014q2-20140408-linux.tar.bz2 && \
	wget --no-check-certificate "https://web.archive.org/web/http://www.open2x.org/open2x/toolchains/arm-open2x-linux-apps-gcc-4.1.1-glibc-2.3.6_i686_linux.tar.bz2.zip" && \
	tar xjf arm-open2x-linux-apps-gcc-4.1.1-glibc-2.3.6_i686_linux.tar.bz2.zip && \
	ln -s crt1.o /opt/open2x/gcc-4.1.1-glibc-2.3.6/arm-open2x-linux/lib/crt0.o

# toolchain definitions
# NB need to coerce the arm-none-eabi compiler to use the old open2x libs and startup files,
# moreover the ELF files are not correctly linked for linux without the -Ttext-segment
ENV PATH=/opt/gcc-arm-none-eabi-4_7-2014q2/bin:$PATH
ENV TC=/opt/open2x/gcc-4.1.1-glibc-2.3.6
ENV CFLAGS="-U_FORTIFY_SOURCE -D__linux__ -mcpu=arm920t -mfloat-abi=soft -mabi=apcs-gnu -mfpu=fpa -mno-thumb-interwork --sysroot=$TC/arm-open2x-linux -I$TC/arm-open2x-linux/include -I/home/include"
ENV LDFLAGS="$CFLAGS -B$TC/arm-open2x-linux/lib -B$TC/lib/gcc/arm-open2x-linux/4.1.1 -L/home/lib -Wl,-Ttext-segment=0x10100"

# additional libraries
RUN	cd /home && mkdir /home/lib /home/include && \
	wget "http://www.zlib.net/zlib-1.3.tar.gz" && tar xzf zlib-1.3.tar.gz && cd zlib-1.3 && \
	CC=arm-none-eabi-gcc CFLAGS="$CFLAGS -Os" ./configure --static --libdir=/home/lib --includedir=/home/include && \
	make AR=arm-none-eabi-ar install
RUN	cd /home && wget --no-check-certificate "https://downloads.sourceforge.net/project/libpng/libpng12/1.2.59/libpng-1.2.59.tar.gz" && \
	tar xzf libpng-1.2.59.tar.gz && cd libpng-1.2.59 && \
	CFLAGS="$CFLAGS -Os" ./configure --host=arm-none-eabi --libdir=/home/lib --includedir=/home/include && \
	make install
