# build container for RG350

FROM --platform=linux/amd64 ubuntu:22.04

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils gcc g++

# toolchain and libraries
# gcw0 toolchain uses gcc 4.9, but we can use the current 2021 od beta toolchain's gcc to get a better optimisation
RUN	wget --no-check-certificate "https://od.abstraction.se/opendingux/toolchain/opendingux-gcw0-toolchain.2021-10-22.tar.xz" && \
	tar xaCf /opt opendingux-gcw0-toolchain.2021-10-22.tar.xz && \
	mv /opt/gcw0-toolchain /opt/gcw0-toolchain-od
RUN	wget --no-check-certificate "https://github.com/Ninoh-FOX/toolchain/releases/download/08-09-2021/opendingux-gcw0-toolchain.2021-09-08.tar.bz2" && \
	tar xjCf /opt opendingux-gcw0-toolchain.2021-09-08.tar.bz2

# toolchain definitions
# NB on newer GKD firmware there's a problem with missing exception handlers in
# libgcc_s.so. Undefining those functions and linking in libgcc_eh solves this.
ENV PATH=/opt/gcw0-toolchain-od/usr/bin:$PATH
ENV TS=/opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot
ENV CFLAGS="--sysroot $TS -I$TS/usr/include/SDL -mabicalls"
ENV LDFLAGS="$CFLAGS -Wl,--dynamic-linker=/lib/ld-uClibc.so.0 -u__register_frame_info -u__deregister_frame_info -L$TS/../lib -lgcc_eh"
ENV CROSS_COMPILE=mipsel-linux-
