# build container for GCW-0

#FROM --platform=linux/386 ubuntu:18.04
FROM --platform=linux/amd64 ubuntu:22.04

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils gcc g++ && \
	apt-get -y --no-install-recommends install libc6-i386 libstdc++6-i386-cross

# toolchain and libraries
# 2014 toolchain uses gcc 4.9, but we can use the current 2021 od beta toolchain's gcc to get a better optimisation
RUN	wget --no-check-certificate "https://od.abstraction.se/opendingux/toolchain/opendingux-gcw0-toolchain.2021-10-22.tar.xz" && \
	tar xaCf /opt opendingux-gcw0-toolchain.2021-10-22.tar.xz && \
	mv /opt/gcw0-toolchain /opt/gcw0-toolchain-od
#RUN	wget --no-check-certificate "https://web.archive.org/web/http://www.gcw-zero.com/files/opendingux-gcw0-toolchain.2014-08-20.tar.bz2" && \
#RUN	wget --no-check-certificate "https://git.libretro.com/libretro-infrastructure/libretro-build-dingux/-/raw/master/toolchain/opendingux-gcw0-toolchain.2014-08-20.tar.bz2" && \
RUN	wget --no-check-certificate "https://github.com/Ninoh-FOX/toolchain/releases/download/08-09-2021/opendingux-gcw0-toolchain.2021-09-08.tar.bz2" && \
	tar xjCf /opt opendingux-gcw0-toolchain.2021-09-08.tar.bz2

# toolchain definitions
ENV PATH=/opt/gcw0-toolchain-od/usr/bin:$PATH
ENV TS=/opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot
ENV CFLAGS="--sysroot $TS -I$TS/usr/include/SDL -mabicalls"
ENV LDFLAGS="$CFLAGS -Wl,--dynamic-linker=/lib/ld-uClibc.so.0"
ENV CROSS_COMPILE=mipsel-linux-
