# build container for legacy (open)dingux with JZ4755:
# dingoo a320, ritmix rzx50, and similar devices

# libs and compiler from: opendingux 2012 toolchain
# TODO: check if odbeta toolchain could be used with the old libs, like gcw-0

# the toolchain is x86 32 bit. However, since github blessed us with actions exclusively running on x86 64 bit...
#FROM --platform=linux/386 debian:bullseye
FROM --platform=linux/amd64 debian:bullseye

ENV UNPRIVILEGED_USER_GROUPS=sudo

# minimal build environment
RUN	apt-get update && \
	apt-get -y --no-install-recommends install sudo make vim git-core wget curl zip bzip2 xz-utils gcc g++ ca-certificates && \
	apt-get -y --no-install-recommends install libc6-i386 libstdc++6-i386-cross

# toolchain and libraries
#RUN	wget --no-check-certificate "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/dingoo-linux/dingux_toolchain_20091022.tar.bz2" && \
RUN	wget --no-check-certificate "https://web.archive.org/web/http://www.treewalker.org/opendingux/opendingux-toolchain.2012-06-16.tar.bz2" && \
	tar xjCf /opt opendingux-toolchain.2012-06-16.tar.bz2

# toolchain definitions
ENV PATH=/opt/opendingux-toolchain/usr/bin:$PATH
ENV TC=/opt/opendingux-toolchain
ENV CFLAGS="--sysroot $TC -I$TC/usr/include/SDL -mabicalls"
ENV LDFLAGS="$CFLAGS"
ENV CROSS_COMPILE=mipsel-linux-
