name: DockerLayer
on: [push, pull_request]
env:
  REGISTRY: ghcr.io

jobs:
  build-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tc: [gp2x, pandora, dingux, opendingux, retrofw]
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: registry login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: build/push container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: "Dockerfile-${{ matrix.tc }}"
        push: true
        provenance: false
        tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/toolchain-${{ matrix.tc }}

